In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/FSP/Salary_Data.csv")
df


YearsExperience  Salary
0               1.1   39343
1               1.3   40205
2               1.5   42731
3               2.0   43525
4               2.2   44891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.3   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9   99000
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872

In [ ]:
x=df.iloc[:,0:1].values
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.3],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [ ]:
y=df.iloc[:,1].values
y

array([ 39343,  40205,  42731,  43525,  44891,  56642,  60150,  54445,
        64445,  57189,  63218,  55794,  56957,  57081,  61111,  67938,
        66029,  83088,  81363,  93940,  91738,  98273,  99000, 113812,
       109431, 105582, 116969, 112635, 122391, 121872])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
x_train

array([[ 7.9],
       [ 8.2],
       [ 2.2],
       [ 1.5],
       [ 9. ],
       [ 3. ],
       [ 5.9],
       [ 4.1],
       [ 3.2],
       [ 9.6],
       [ 1.3],
       [ 5.1],
       [ 1.1],
       [ 4.9],
       [10.5],
       [10.3],
       [ 3.7],
       [ 3.3],
       [ 4. ],
       [ 4. ],
       [ 2.9]])

In [ ]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
m=model.coef_
m

array([9128.22537161])

In [ ]:
c=model.intercept_
c

np.float64(26459.122772411232)

In [ ]:
m*2.3+c

array([47454.04112712])

In [ ]:
model.predict([[2.3]])

array([47454.04112712])

In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [2]:
import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/FSP/Employee_Data.csv")
df

Department  WorkedHours  Certification  YearsExperience  Salary
0   Development         2300              0              1.1   39343
1       Testing         2100              1              1.3   46205
2   Development         2104              2              1.5   37731
3   UX Designer         1200              1              2.0   43525
4       Testing         1254              2              2.2   39891
5   UX Designer         1236              1              2.9   56642
6   Development         1452              2              3.0   60150
7       Testing         1789              1              3.2   54445
8   UX Designer         1645              1              3.2   64445
9   UX Designer         1258              0              3.7   57189
10      Testing         1478              3              3.9   63218
11  Development         1257              2              4.0   55794
12  Development         1596              1              4.0   56957
13      Testing         1256              2              4.1   57081
14  UX Designer         1489              3              4.5   61111
15  Development         1236              3              4.9   67938
16      Testing         2311              2              5.1   66029
17  UX Designer         2245              3              5.3   83088
18  Development         2365              1              5.9   81363
19  Development         1500              3              6.0   93940
20      Testing         1456              2              6.8   91738
21      Testing         1760              1              7.1   98273
22  UX Designer         2400              4              7.9  101302
23  Development         2148              3              8.2  113812
24  UX Designer         1450              2              8.7  109431
25  UX Designer         1000              4              9.0  105582
26      Testing         1540              3              9.5  116969
27  Development         1500              2              9.6  112635
28      Testing         3000              4             10.3  122391
29  UX Designer         2100              3             10.5  121872

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Department       30 non-null     object 
 1   WorkedHours      30 non-null     int64  
 2   Certification    30 non-null     int64  
 3   YearsExperience  30 non-null     float64
 4   Salary           30 non-null     int64  
dtypes: float64(1), int64(3), object(1)
memory usage: 1.3+ KB


In [5]:
x=df.iloc[:,0:4].values
x

array([['Development', 2300, 0, 1.1],
       ['Testing', 2100, 1, 1.3],
       ['Development', 2104, 2, 1.5],
       ['UX Designer', 1200, 1, 2.0],
       ['Testing', 1254, 2, 2.2],
       ['UX Designer', 1236, 1, 2.9],
       ['Development', 1452, 2, 3.0],
       ['Testing', 1789, 1, 3.2],
       ['UX Designer', 1645, 1, 3.2],
       ['UX Designer', 1258, 0, 3.7],
       ['Testing', 1478, 3, 3.9],
       ['Development', 1257, 2, 4.0],
       ['Development', 1596, 1, 4.0],
       ['Testing', 1256, 2, 4.1],
       ['UX Designer', 1489, 3, 4.5],
       ['Development', 1236, 3, 4.9],
       ['Testing', 2311, 2, 5.1],
       ['UX Designer', 2245, 3, 5.3],
       ['Development', 2365, 1, 5.9],
       ['Development', 1500, 3, 6.0],
       ['Testing', 1456, 2, 6.8],
       ['Testing', 1760, 1, 7.1],
       ['UX Designer', 2400, 4, 7.9],
       ['Development', 2148, 3, 8.2],
       ['UX Designer', 1450, 2, 8.7],
       ['UX Designer', 1000, 4, 9.0],
       ['Testing', 1540, 3, 9.5],
       ['D

In [7]:
from sklearn.preprocessing import LabelEncoder
en=LabelEncoder()
x[:,0]=en.fit_transform(x[:,0])
x

array([[0, 2300, 0, 1.1],
       [1, 2100, 1, 1.3],
       [0, 2104, 2, 1.5],
       [2, 1200, 1, 2.0],
       [1, 1254, 2, 2.2],
       [2, 1236, 1, 2.9],
       [0, 1452, 2, 3.0],
       [1, 1789, 1, 3.2],
       [2, 1645, 1, 3.2],
       [2, 1258, 0, 3.7],
       [1, 1478, 3, 3.9],
       [0, 1257, 2, 4.0],
       [0, 1596, 1, 4.0],
       [1, 1256, 2, 4.1],
       [2, 1489, 3, 4.5],
       [0, 1236, 3, 4.9],
       [1, 2311, 2, 5.1],
       [2, 2245, 3, 5.3],
       [0, 2365, 1, 5.9],
       [0, 1500, 3, 6.0],
       [1, 1456, 2, 6.8],
       [1, 1760, 1, 7.1],
       [2, 2400, 4, 7.9],
       [0, 2148, 3, 8.2],
       [2, 1450, 2, 8.7],
       [2, 1000, 4, 9.0],
       [1, 1540, 3, 9.5],
       [0, 1500, 2, 9.6],
       [1, 3000, 4, 10.3],
       [2, 2100, 3, 10.5]], dtype=object)

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)
x

array([[-1.22474487,  1.23991938, -1.89010336, -1.51005294],
       [ 0.        ,  0.81661831, -0.97553722, -1.43837321],
       [-1.22474487,  0.82508433, -0.06097108, -1.36669348],
       [ 1.22474487, -1.0882365 , -0.97553722, -1.18749416],
       [ 0.        , -0.97394521, -0.06097108, -1.11581443],
       [ 1.22474487, -1.01204231, -0.97553722, -0.86493538],
       [-1.22474487, -0.55487715, -0.06097108, -0.82909552],
       [ 0.        ,  0.15838515, -0.97553722, -0.75741579],
       [ 1.22474487, -0.14639162, -0.97553722, -0.75741579],
       [ 1.22474487, -0.96547919, -1.89010336, -0.57821647],
       [ 0.        , -0.49984801,  0.85359507, -0.50653674],
       [-1.22474487, -0.96759569, -0.06097108, -0.47069688],
       [-1.22474487, -0.25010038, -0.97553722, -0.47069688],
       [ 0.        , -0.9697122 , -0.06097108, -0.43485702],
       [ 1.22474487, -0.47656645,  0.85359507, -0.29149756],
       [-1.22474487, -1.01204231,  0.85359507, -0.1481381 ],
       [ 0.        ,  1.

In [10]:
y=df.iloc[:,4].values
y

array([ 39343,  46205,  37731,  43525,  39891,  56642,  60150,  54445,
        64445,  57189,  63218,  55794,  56957,  57081,  61111,  67938,
        66029,  83088,  81363,  93940,  91738,  98273, 101302, 113812,
       109431, 105582, 116969, 112635, 122391, 121872])

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
x_train

array([[ 1.22474487,  1.45156992,  1.76816121,  0.92705781],
       [-1.22474487,  0.91821057,  0.85359507,  1.03457741],
       [ 0.        , -0.97394521, -0.06097108, -1.11581443],
       [-1.22474487,  0.82508433, -0.06097108, -1.36669348],
       [ 1.22474487, -1.51153757,  1.76816121,  1.32129632],
       [-1.22474487, -0.55487715, -0.06097108, -0.82909552],
       [-1.22474487,  1.37749223, -0.97553722,  0.21026054],
       [ 0.        , -0.9697122 , -0.06097108, -0.43485702],
       [ 0.        ,  0.15838515, -0.97553722, -0.75741579],
       [-1.22474487, -0.4532849 , -0.06097108,  1.5363355 ],
       [ 0.        ,  0.81661831, -0.97553722, -1.43837321],
       [ 0.        ,  1.26320094, -0.06097108, -0.07645838],
       [-1.22474487,  1.23991938, -1.89010336, -1.51005294],
       [-1.22474487, -1.01204231,  0.85359507, -0.1481381 ],
       [ 1.22474487,  0.81661831,  0.85359507,  1.85889428],
       [ 0.        ,  2.72147313,  1.76816121,  1.78721455],
       [ 1.22474487, -0.

In [12]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [13]:
y_pref=model.predict(x_test)
y_pref

array([ 77260.28538161,  91489.66768656,  60623.76776817,  78948.59438096,
        66922.19578438,  87183.03784726, 111667.94813783,  43761.75849234,
       105203.02063621])

In [14]:
y_test

array([ 83088,  98273,  63218,  93940,  61111,  91738, 116969,  43525,
       109431])

In [15]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
mae=mean_absolute_error(y_test,y_pref)
mae

5592.070270902846